modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
[[mods]] #mandatory
modId="undead_horse_re" #mandatory
version="1.0" #mandatory
displayName="Good Undead Horses" #mandatory
authors="SoftSilver" #optional
description='''
Minor rework to the undead horses.'''
